/**
 * Sales workflow constants: sheet names, statuses, task types, and tab headers.
 */

var SW_SHEETS = {
  MASTER: '00_Master Appointments',
  TASKS: '_SalesTaskQueue',
  LOG: '_SalesTaskLog',
  CONFIG: '_SalesWorkflowConfig',
  TEMPLATES: '_SalesWorkflowTemplates',
  USERS: '_SalesWorkflowUsers',
  DATA_CLEANUP: '_SalesDataCleanup',
  APPOINTMENT_ARTIFACTS: '_AppointmentArtifacts',
  EXTERNAL_BOOKING_EVENTS: '_ExternalBookingEvents',
  INBOX_LOG: '_SalesInboxLog',
  READ_MODEL_TASKS: '_SW_TaskReadModel',
  READ_MODEL_CUSTOMERS: '_SW_CustomerReadModel',
  READ_MODEL_DIAMONDS: '_SW_DiamondReadModel',
  READ_MODEL_DIAMOND_ROOTS: '_SW_DiamondRootReadModel',
  READ_MODEL_APPOINTMENTS: '_SW_AppointmentReadModel',
  READ_MODEL_CALENDAR_MONTHS: '_SW_CalendarMonthReadModel',
  READ_MODEL_PAYMENTS: '_SW_PaymentReadModel',
  READ_MODEL_ADMIN_DASHBOARD: '_SW_AdminDashboardReadModel',
  READ_MODEL_INBOX: '_SW_InboxReadModel',
  READ_MODEL_META: '_SW_ReadModelMeta',
  ROSTER: '10_Roster_Schedule',
  SCHEDULE_CHANGES: 'Schedule Changes',
  DROPDOWN: 'Dropdown'
};

var SW_EXTERNAL_BOOKING_EVENT_HEADERS = [
  'ReceivedAt',
  'Provider',
  'Action',
  'ProviderAppointmentID',
  'CalendarID',
  'AppointmentTypeID',
  'RawPayloadJSON',
  'SignatureVerified',
  'Status',
  'Attempts',
  'ProcessedAt',
  'ResolvedUID',
  'MasterRow',
  'ResultJSON',
  'Error',
  'TestRunID'
];
var SW_STATUSES = {
  PENDING: 'Pending',
  COMPLETED: 'Completed',
  BLOCKED: 'Blocked',
  SNOOZED: 'Snoozed'
};
var SW_INACTIVE_APPOINTMENT_BLOCK_REASON = 'Appointment is no longer active/current.';
var SW_TASKS = {
  ASSIGN: 'ASSIGN_APPOINTMENT',
  WELCOME: 'SEND_WELCOME',
  HYBRID: 'SEND_HYBRID_WELCOME',
  MAP: 'SEND_MAP_INSTRUCTIONS',
  REVIEW: 'REVIEW_APPOINTMENT',
  CHECKLIST: 'APPOINTMENT_DAY_CHECKLIST',
  PROCESS: 'PROCESS_APPOINTMENT_DATA',
  APPROVE: 'APPROVE_RECAP_MESSAGE',
  FINAL: 'SEND_FINAL_RECAP',
  POST_CONSULT_STATUS: 'POST_CONSULT_CLIENT_STATUS',
  START_3D: 'START_3D_DESIGN',
  RECORD_3D_DEADLINE: 'RECORD_3D_DEADLINE',
  REQUEST_WAX: 'REQUEST_WAX_PRINT',
  UPDATE_WAX: 'UPDATE_WAX_REQUEST',
  DIAMOND_PROPOSE: 'PROPOSE_DIAMONDS',
  DIAMOND_QUOTE: 'PREPARE_DV_QUOTATION',
  DIAMOND_ORDER: 'ORDER_DIAMONDS',
  DIAMOND_TRACK: 'TRACK_DIAMONDS',
  DIAMOND_DELIVERY: 'CONFIRM_DIAMOND_DELIVERY',
  DIAMOND_DECISIONS: 'RECORD_DIAMOND_DECISIONS',
  DIAMOND_RETURN: 'RETURN_DIAMONDS',
  DIAMOND_ORDER_ACK_REP: 'ACK_DIAMONDS_ORDERED_ASSIGNED_REP',
  DIAMOND_ORDER_ACK_JOC: 'ACK_DIAMONDS_ORDERED_JOC',
  DIAMOND_ETA_REP: 'REVIEW_DIAMOND_ETA_ASSIGNED_REP',
  DIAMOND_ETA_JOC: 'REVIEW_DIAMOND_ETA_JOC',
  DATA_CLEANUP_REVIEW: 'CUSTOMER_DATA_CLEANUP_REVIEW',
  DATA_CLEANUP_CONFIRM: 'CUSTOMER_DATA_CLEANUP_CONFIRM',
  DATA_CLEANUP_REVISE: 'CUSTOMER_DATA_CLEANUP_REVISE'
};
var SW_OWNER_ROLES = {
  SYSTEM: 'System',
  SALES_REP: 'Client Advisor',
  JOC: 'JOC',
  DIAMOND_ORDER_ADMIN: 'DIAMOND_ORDER_ADMIN',
  DIAMOND_ORDER_ASSISTANT: 'DIAMOND_ORDER_ASSISTANT'
};
var SW_TASK_HEADERS = [
  'TaskID',
  'RootApptID',
  'APPT_ID',
  'Customer Name',
  'Brand',
  'Visit Date',
  'Visit Time',
  'Visit Type',
  'Lifecycle Stage',
  'Task Type',
  'Task Title',
  'Owner Role',
  'Intended Owner',
  'Intended Owner Email',
  'Current Owner',
  'Current Owner Email',
  'Coverage Reason',
  'Due At',
  'Status',
  'Dependency TaskID',
  'Created At',
  'Updated At',
  'Completed By',
  'Completed By Email',
  'Completed At',
  'Claimed By',
  'Claimed At',
  'Last Event',
  'Payload JSON',
  'Template Key',
  'Instructions',
  'Primary Action',
  'Snooze Until',
  'Snooze Reason',
  'Snoozed By',
  'Snoozed At'
];
var SW_TASK_LIST_HEADERS = [
  'TaskID',
  'RootApptID',
  'APPT_ID',
  'Customer Name',
  'Brand',
  'Visit Date',
  'Visit Time',
  'Visit Type',
  'Lifecycle Stage',
  'Task Type',
  'Task Title',
  'Owner Role',
  'Intended Owner',
  'Intended Owner Email',
  'Current Owner',
  'Current Owner Email',
  'Coverage Reason',
  'Due At',
  'Status',
  'Primary Action',
  'Snooze Until',
  'Snooze Reason'
];
var SW_TASK_READ_MODEL_HEADERS = [
  'TaskID',
  'RootApptID',
  'APPT_ID',
  'Customer Name',
  'Brand',
  'Visit Date',
  'Visit Time',
  'Visit Type',
  'Lifecycle Stage',
  'Task Type',
  'Task Title',
  'Owner Role',
  'Intended Owner',
  'Intended Owner Email',
  'Current Owner',
  'Current Owner Email',
  'Coverage Reason',
  'Due At',
  'Status',
  'Primary Action',
  'Snooze Until',
  'Snooze Reason',
  'Row Number',
  'Pending Like?',
  'Due Now?',
  'Search Text'
];
var SW_CUSTOMER_READ_MODEL_HEADERS = [
  'RootApptID',
  'Latest APPT_ID',
  'Master Row',
  'Customer Name',
  'Email',
  'Phone',
  'Brand',
  'Client Advisor',
  'Client Advisor Email',
  'JOC',
  'JOC Email',
  'Latest Visit Date',
  'Latest Visit Time',
  'Latest Visit Type',
  'Next Visit',
  'Last Visit',
  'Appointment Count',
  'Active Appointment Count',
  'Active?',
  'Stage Key',
  'Stage Label',
  'Sales Stage',
  'Conversion Status',
  'Custom Order Status',
  'In Production Status',
  'Center Stone Status',
  'SO#',
  'Order Total',
  'Paid-to-Date',
  'Remaining Balance',
  'Last Payment Date',
  'Quotation URL',
  'Client Folder',
  'Client Status Report URL',
  '3D Tracker URL',
  '3D Deadline',
  'Production Deadline',
  'Wax Print Status',
  'Wax Deadline (Admin)',
  'DV Stones Summary',
  'Next Steps',
  'Updated At',
  'AI Brief?',
  'Review Flag Count',
  'Latest AI Brief Updated At',
  'Source Rows JSON',
  'Search Text'
];
var SW_DIAMOND_READ_MODEL_HEADERS = [
  'Source Row',
  'RootApptID',
  'Customer Name',
  'Customer Appt Time & Date',
  'Client Advisor',
  'JOC',
  'Company',
  'Vendor',
  'Stone Type',
  'Shape',
  'Carat',
  'Color',
  'Clarity',
  'LAB',
  'Certificate No',
  'Measurements',
  'L/W Ratio',
  'Order Status',
  'Stone Status',
  'Stone Decision',
  'Request Date',
  'Requested By',
  'Ordered By',
  'Purchased / Ordered Date',
  'Memo/ Invoice Date',
  'Return DUE DATE',
  'Tracking ETA',
  'Tracking Status',
  'Carrier',
  'Tracking Number',
  'Tracking URL',
  'Tracking Notes',
  'Loupe360 Order #',
  'Invoice Number',
  'Loupe360 Last Sync At',
  'Diamond Label',
  'Source Spreadsheet URL',
  'Source Spreadsheet Name',
  'Source Tab',
  'Search Text'
];
var SW_DIAMOND_ROOT_READ_MODEL_HEADERS = [
  'RootApptID',
  'Customer Name',
  'Client Advisor',
  'JOC',
  'Company',
  'Stone Count',
  'Proposing Count',
  'On The Way Count',
  'Delivered Count',
  'In Stock Count',
  'Return Count',
  'Purchase Count',
  'Issue Count',
  'Missing Assignment Count',
  'Earliest Return Due',
  'Latest Tracking ETA',
  'Summary',
  'Source Rows JSON',
  'Updated At',
  'Search Text'
];
var SW_APPOINTMENT_READ_MODEL_HEADERS = [
  'Row Number',
  'APPT_ID',
  'RootApptID',
  'UID',
  'Customer Name',
  'Email',
  'Phone',
  'Brand',
  'Booked At',
  'Canceled At',
  'Rescheduled From UID',
  'Rescheduled To UID',
  'Visit Date',
  'Visit Time',
  'Visit At Ms',
  'Visit Type',
  'Diamond Type',
  'Status',
  'Active?',
  'Client Advisor',
  'Client Advisor Email',
  'JOC',
  'JOC Email',
  'Client Folder',
  'Client Status Report URL',
  'Quotation URL',
  '3D Tracker URL',
  'Sales Stage',
  'Conversion Status',
  'Custom Order Status',
  'In Production Status',
  'Next Steps',
  'Design Request',
  '3D Deadline',
  'Production Deadline',
  'Wax Print Status',
  'Wax Deadline (Admin)',
  'Wax Request URL',
  'Center Stone Status',
  'DV Stones Summary',
  'DV Customer Looking For',
  'DV Variety Strategy',
  'DV Customer Requirements (JSON)',
  'SO#',
  'Order Folder',
  'Source',
  'Budget Min',
  'Budget Max',
  'Order Total',
  'Paid-to-Date',
  'Remaining Balance',
  'Last Payment Date',
  'Order Date',
  'Updated At',
  '3D Deadline Moves',
  'Production Deadline Moves',
  'Search Text'
];
var SW_CALENDAR_MONTH_READ_MODEL_HEADERS = [
  'Month Key',
  'Month Label',
  'Appointment Count',
  'Appointments JSON',
  'Built At',
  'Search Text'
];
var SW_PAYMENT_READ_MODEL_HEADERS = [
  'Source Row',
  'RootApptID',
  'SO#',
  'Key',
  'Brand',
  'Payment ID',
  'Doc Type',
  'Doc Number',
  'Doc Status',
  'Method',
  'Payment At',
  'Payment At Ms',
  'Amount Net',
  'Amount Gross',
  'Balance Due',
  'Order Total',
  'Search Text'
];
var SW_ADMIN_DASHBOARD_READ_MODEL_HEADERS = [
  'Key',
  'Window Preset',
  'Brand',
  'Client Advisor',
  'JOC',
  'Include Closed',
  'Built At',
  'Payload JSON',
  'Payload Bytes',
  'Search Text'
];
var SW_INBOX_LOG_HEADERS = [
  'NotificationID',
  'Created At',
  'Kind',
  'Event Type',
  'Title',
  'Body',
  'Badge Label',
  'Sender Name',
  'Sender Email',
  'Sender Role',
  'Recipient Mode',
  'Role Targets JSON',
  'User Targets JSON',
  'Visible Emails JSON',
  'RootApptID',
  'APPT_ID',
  'Previous APPT_ID',
  'Customer Name',
  'Brand',
  'Visit Date',
  'Visit Time',
  'Previous Visit Date',
  'Previous Visit Time',
  'Booked At',
  'Booked Within 24 Hours?',
  'Fingerprint',
  'Payload JSON'
];
var SW_INBOX_READ_MODEL_HEADERS = [
  'Month Key',
  'Notification Count',
  'Notifications JSON',
  'Built At',
  'Search Text'
];
var SW_READ_MODEL_META_HEADERS = [
  'Model',
  'Version',
  'Built At',
  'Expires At',
  'Source Sheet',
  'Source Rows',
  'Output Rows',
  'Build Ms',
  'Status',
  'Error',
  'Invalidated At',
  'Notes'
];
var SW_LOG_HEADERS = [
  'Event At',
  'Event Type',
  'TaskID',
  'RootApptID',
  'APPT_ID',
  'Task Type',
  'Actor Name',
  'Actor Email',
  'From Owner',
  'To Owner',
  'Status',
  'Details JSON'
];
var SW_CONFIG_HEADERS = [
  'Section',
  'Key',
  'Value',
  'Role',
  'Name',
  'Email',
  'Active?',
  'Priority',
  'Notes'
];
var SW_TEMPLATE_HEADERS = [
  'Task Type',
  'Task Title',
  'Instructions',
  'Template',
  'Attachment Label',
  'Attachment URL',
  'Checklist JSON',
  'Primary Action'
];
var SW_AUTH_USER_HEADERS = [
  'Email',
  'Name',
  'Roles',
  'Active?',
  'Password Salt',
  'Password Hash',
  'Temporary Password?',
  'Last Login At',
  'Notes'
];
var SW_EMPLOYEE_SCHEDULE_HEADERS = [
  'Rep',
  'Email',
  'Role',
  'Active?',
  'Mon',
  'Tue',
  'Wed',
  'Thu',
  'Fri',
  'Sat',
  'Sun',
  'Default JOC',
  'Assisted Coverage Enabled?',
  'Assisted Coverage Partner',
  'Lab Diamond',
  'Natural Diamond',
  'General Appointment',
  'Skill Notes',
  'Updated At',
  'Updated By'
];
var SW_SCHEDULE_CHANGE_HEADERS = [
  'Rep Name',
  'Email',
  'Role',
  'Change Date',
  'Change Type',
  'Available From',
  'Available Until',
  'Notes',
  'Updated At',
  'Updated By'
];
var SW_DATA_CLEANUP_HEADERS = [
  'CaseID',
  'Campaign ID',
  'RootApptID',
  'APPT_ID',
  'Customer Name',
  'Brand',
  'Client Advisor',
  'Client Advisor Email',
  'JOC',
  'JOC Email',
  'Stage Key',
  'Current Sales Stage',
  'Current Conversion Status',
  'Current Custom Order Status',
  'Current In Production Status',
  'Last Touch At',
  'Stale Days',
  'Status',
  'Campaign Tab?',
  'Proposal JSON',
  'Proposed By',
  'Proposed By Email',
  'Proposed Role',
  'Proposed At',
  'Confirmation By',
  'Confirmation Email',
  'Confirmed At',
  'Return Reason',
  'Returned By',
  'Returned At',
  'Revision Count',
  'Applied At',
  'Applied Result JSON',
  'Created At',
  'Updated At'
];
