server:
  address: ":8080"

database:
  path: "./local.db"

logging:
  level: "info"

storage:
  local_path: "./files"
  url_prefix: "/files/"

scheduler:
  interval: "5m"

auth:
  jwt_secret: "local-dev-secret-please-change"
  token_ttl_minutes: 15

seed:
  admin_email: "admin@example.com"
  admin_password: "changeme123"
  admin_role: "admin"
